2024-07-17 19:14:39,557 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Configure stats pid to 1339909
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Loading settings from /home/yunkwan/.config/wandb/settings
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Loading settings from /home/yunkwan/project/radarclip/wandb/settings
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_core': 'true', 'project': 'teacher_student_distillation', 'entity': 'kycl0131', 'root_dir': '/home/yunkwan/project/radarclip', 'run_id': 'dhk41z54', 'sweep_param_path': '/home/yunkwan/project/radarclip/wandb/sweep-3e81xg3r/config-dhk41z54.yaml', 'sweep_id': '3e81xg3r'}
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'distillation.py', 'program_abspath': '/home/yunkwan/project/radarclip/distillation.py', 'program': '/home/yunkwan/project/radarclip/distillation.py'}
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_init.py:_log_setup():520] Logging user logs to /home/yunkwan/project/radarclip/wandb/run-20240717_191439-dhk41z54/logs/debug.log
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_init.py:_log_setup():521] Logging internal logs to /home/yunkwan/project/radarclip/wandb/run-20240717_191439-dhk41z54/logs/debug-internal.log
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_init.py:init():560] calling init triggers
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_init.py:init():567] wandb.init called with sweep_config: {'alpha': 0.7, 'batch_size': 256, 'epochs': 30, 'feature_loss_weight': 0.5, 'temperature': 8}
config: {}
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_init.py:init():610] starting backend
2024-07-17 19:14:39,558 INFO    Thread-9  :1339909 [wandb_init.py:init():614] setting up manager
2024-07-17 19:14:39,561 INFO    Thread-9  :1339909 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-17 19:14:39,561 INFO    Thread-9  :1339909 [wandb_init.py:init():622] backend started and connected
2024-07-17 19:14:39,567 INFO    Thread-9  :1339909 [wandb_run.py:_config_callback():1382] config_cb None None {'alpha': 0.7, 'batch_size': 256, 'epochs': 30, 'feature_loss_weight': 0.5, 'temperature': 8}
2024-07-17 19:14:39,569 INFO    Thread-9  :1339909 [wandb_init.py:init():711] updated telemetry
2024-07-17 19:14:39,569 INFO    Thread-9  :1339909 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-07-17 19:14:39,820 INFO    Thread-9  :1339909 [wandb_run.py:_on_init():2402] communicating current version
2024-07-17 19:14:39,820 INFO    Thread-9  :1339909 [wandb_run.py:_on_init():2411] got version response 
2024-07-17 19:14:39,821 INFO    Thread-9  :1339909 [wandb_init.py:init():795] starting run threads in backend
2024-07-17 19:14:39,978 INFO    Thread-9  :1339909 [wandb_run.py:_console_start():2380] atexit reg
2024-07-17 19:14:39,978 INFO    Thread-9  :1339909 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-07-17 19:14:39,978 INFO    Thread-9  :1339909 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-07-17 19:14:39,978 INFO    Thread-9  :1339909 [wandb_run.py:_redirect():2325] Redirects installed.
2024-07-17 19:14:39,979 INFO    Thread-9  :1339909 [wandb_init.py:init():838] run started, returning control to user process
2024-07-17 19:34:40,184 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:34:40,184 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"errors":[{"message":"context deadline exceeded"}]}
2024-07-17 19:35:36,404 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:35:36,404 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"errors":[{"message":"context deadline exceeded"}]}
2024-07-17 19:39:12,037 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:39:12,038 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:39:15,025 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:39:15,025 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:39:15,025 INFO    Thread-1  :1339909 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2024-07-17 19:39:38,816 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:39:38,816 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:39:49,031 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:39:49,031 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:42:57,291 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:42:57,291 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:43:13,576 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:43:13,576 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:43:13,576 INFO    Thread-1  :1339909 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yunkwan/anaconda3/envs/smallcap/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2024-07-17 19:43:44,761 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:43:44,762 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:43:55,691 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:43:55,691 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:44:15,545 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:44:15,545 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:44:58,194 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:44:58,194 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:46:05,001 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:46:05,001 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:48:38,933 ERROR   Thread-1  :1339909 [internal_api.py:execute():344] 500 response executing GraphQL.
2024-07-17 19:48:38,933 ERROR   Thread-1  :1339909 [internal_api.py:execute():345] {"error":"An internal error occurred. Please contact support."}
2024-07-17 20:24:21,729 INFO    Thread-9  :1339909 [wandb_run.py:_finish():2109] finishing run kycl0131/teacher_student_distillation/dhk41z54
2024-07-17 20:24:21,729 INFO    Thread-9  :1339909 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 0
2024-07-17 20:24:21,729 INFO    Thread-9  :1339909 [wandb_run.py:_restore():2332] restore
2024-07-17 20:24:21,729 INFO    Thread-9  :1339909 [wandb_run.py:_restore():2338] restore done
2024-07-17 20:24:24,708 INFO    Thread-9  :1339909 [wandb_run.py:_footer_history_summary_info():3991] rendering history
2024-07-17 20:24:24,709 INFO    Thread-9  :1339909 [wandb_run.py:_footer_history_summary_info():4023] rendering summary
2024-07-17 20:24:24,712 INFO    Thread-9  :1339909 [wandb_run.py:_footer_sync_info():3950] logging synced files
